### ISSUE TITLE
not an issue just a question

### ISSUE THREAD

**Issue by h09s** [NickJordan289/nopixel4-lockpick-solver#1]
would it be possible to make a bot that auto solves roof running job??

**Comment by NickJordan289** [comment]
Probably.
Would start by looking at how the game functions.
https://github.com/MaximilianAdF/NoPixel-MiniGames-4.0/blob/main/app/puzzles/roof-running/utils.ts

Tricky part is obviously deciding which moves to make without causing it to be unsolvable.
